### ISSUE TITLE
No such file or directory: 'esearch_output.txt'

### ISSUE THREAD

**Issue by sroblet** [gjeunen/reference_database_creator#10]
Hi, 

When I'm trying to run the function "crabs db_download" on NCBI database, it leads to an error message :

 crabs db_download --source ncbi --database nucleotide --query '16S' --output 16S_ncbi.fasta --keep_original yes --email sylvain.roblet31@gmail.com --batchsize 5000

downloading sequences from NCBI
looking up the number of sequences that match the query
Traceback (most recent call last):
  File "/home/CRABS/reference_database_creator/crabs", line 1409, in <module>
    main()
  File "/home/CRABS/reference_database_creator/crabs", line 1406, in main
    args.func(args)
  File "/home/CRABS/reference_database_creator/crabs", line 72, in db_download
    ncbi_download = wget_ncbi(QUERY, DATABASE, EMAIL, BATCHSIZE, OUTPUT)
  File "/home/CRABS/reference_database_creator/function/module_db_download.py", line 22, in wget_ncbi
    with open('esearch_output.txt', 'r') as file_in:
FileNotFoundError: [Errno 2] No such file or directory: 'esearch_output.txt'**_

Could you please help me with this issue,
Thanks a lot !

**Comment by hughcross** [comment]
Thanks for the input, Eldridge. @sroblet let me know if adding the `--keep_original` flag fixes it. I still suggest modifying your query search terms, as mentioned above. We will be adding to the documentation on that to help people build good queries.

**Comment by gjeunen** [comment]
Hello @sroblet, for 16S and 12S I would use the following query:

```
'16S[All Fields] AND (animals[filter] AND mitochondrion[filter] AND ("1"[SLEN] : "50000"[SLEN]))'
```

I just checked and this should download ~500,000 sequences. Please let me know if this works for you. If not, I'll have a deeper look into the code. The error message you received earlier is most likely due to the fact that NCBI servers timed out or cut the connection, which can happen if they receive high traffic volume.

Best regards,
Gert-Jan

**Comment by sroblet** [comment]
Hi, 
Thanks a lot, It worked with this query :) 
For NCBI it's ok now, but i have new issues with MitoFish database : 

crabs db_download --source mitofish --output mitofish.fasta --keep_original yes

downloading sequences from the MitoFish database
Traceback (most recent call last):
  File "/home/sroblet/crabs/reference_database_creator/crabs", line 1409, in <module>
    main()
  File "/home/sroblet/crabs/reference_database_creator/crabs", line 1406, in main
    args.func(args)
  File "/home/sroblet/crabs/reference_database_creator/crabs", line 96, in db_download
    dl_file = mitofish_download(url)
  File "/home/sroblet/crabs/reference_database_creator/function/module_db_download.py", line 139, in mitofish_download
    os.remove('complete_partial_mitogenomes.zip')
FileNotFoundError: [Errno 2] No such file or directory: 'complete_partial_mitogenomes.zip'

Thanks in advance for your help with this new issue ;)

**Comment by gjeunen** [comment]
Hello @sroblet,

Glad this worked out for you!

For the new issue, it seems that the hosting location of the MitoFish database has recently been changed. Hence, CRABS is trying to grab the data from a url that is no longer active. I'll try to get this fixed in the coming hours. I'll let you know once it is fixed, but please remember that the fix will initially only be available for the GitHub version of CRABS. It might take a while before the CRABS version is updated in Docker or conda.

Best regards,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @sroblet,

The issue with regards to the `db_download -s mitofish` should now be fixed. Could you please let me know if you can run the following command without issue once you've updated CRABS to the latest GitHub version?

```
crabs db_download -s mitofish -o mitofish.fasta
```

Best regards,
Gert-Jan

**Comment by sroblet** [comment]
Hello @gjeunen, 
I've done it this morning with the new update and it worked, thanks a lot !
db_merge worked as well :) I'm currently doing the insilico PCR on the merged database and i have a question about it, i will post it in a new issue.
Thanks again, you have made an amazing job !

**Comment by sroblet** [comment]
Hi again, 

I think that there is also an URL problem with the database taxonomy.
I can't extract nucl_gb.accession2taxid.gz even when i try to do it manually..

downloading taxonomy information
nucl_gb.accession2t  99%[==================> ]   2,07G   341KB/s    in 37m 26s 
nucl_gb.accession2t 100%[+++++++++++++++++++>]   2,10G   978KB/s    in 68s     
unzipping nucl_gb.accession2taxid.gz...

gzip: nucl_gb.accession2taxid.gz: invalid compressed data--format violated
taxdump.tar.gz      100%[===================>]  57,12M  1,10MB/s    in 56s     
removing intermediary files

**Comment by gjeunen** [comment]
Hello @sroblet,

I just ran the `db_download -s taxonomy` code and everything seems to work fine on my end. Given that CRABS on your end is able to download the initial zipped files also indicates that there is no issue with the URL. 

The error message is pointing towards a problem of the files that are being downloaded, which seem to be corrupt. This seems only to be the case for the large ~2GB file though (no error message for the second set of files "taxdump.tar.gz"). My best guess at this point is that you're experiencing an unstable connection to the NCBI servers, which are causing some issues by corrupting files when being downloaded over this unstable connection. This unstable connection could be due to firewall settings, internet speed, etc. The reason I think this is the issue, is that the output you posted states it took over 37 minutes to download nucl_gb.accession2taxid.gz, while I don't think I've seen it take more than 5 minutes on my end.

Given the length of download time and the file size, another issue could be the "ftp" protocol to download the files that is implemented in CRABS. I've, therefore, changed it to an "https" protocol. **Could you please update the CRABS code with the latest version and try again to see if this fixes the issue?**

My apologies for the errors you're encountering. At first glance, they all seem to stem from an unstable connection to the NCBI servers (even the "-" presence in your other post). Luckily, CRABS only uses this connection in the `db_download -s ncbi` and `db_download -s taxonomy` functions. So, I hope you won't encounter too many errors from now onwards. In the meantime, I'll try to find a general workaround for this issue for future use.

Best regards,
Gert-Jan
