### ISSUE TITLE
seq_cleanup --species and --nans arguments

### ISSUE THREAD

**Issue by slambrechts** [gjeunen/reference_database_creator#39]
Hi,

For the databases I'm creating, I would like to discard sequences for which the species name is unspecified, but retain sequences for which the species name is specified while other taxonomic levels are unspecified (If a species name is known, filling the blanks for the higher taxonomic levels manually is ok for me). Can I do this in CRABS like so:

`crabs seq_cleanup --species yes --nans 7
`?

Kind regards,
Sam

**Comment by gjeunen** [comment]
Hello @slambrechts,

You can leave the `--nans` parameter out of your line of code to accomplish your goal. You could also set the `--enviro` parameter to `yes` to remove environmental sequences. Your code might look something like this (I've added the parameters with default settings, so that you know which ones you might need to change to suite your reference database):

```
crabs seq_cleanup -i input.tsv -o output.tsv -min DEFAULT -max DEFAULT -n DEFAULT -e yes -s yes
```

**Comment by slambrechts** [comment]
Hi @gjeunen,

Thank you for the clear explanation!

Best,
Sam
