### ISSUE TITLE
"pre-trimmed" sequences

### ISSUE THREAD

**Issue by laninsky** [gjeunen/reference_database_creator#4]
Kia ora GJ - more of a comment than a question, but in labs I've come through it has been pretty common practice to trim the primer sequence off the fragments of interest, because you are mostly sequencing primer, not actual biological sequence. I'm assuming a lot of sequences uploaded to the databases might be in the same boat when targetting "common regions". This means the insilico pcr step will chuck out these "good sequences" when it can't find the primer sites on each end. I'm wondering whether it would be worth warning people about this? I understand why you have implemented it the way you have, but it might be unexpected behavior for some people.

**Comment by gjeunen** [comment]
Hello laninski,

You are right that when people are barcoding an organism, the common practice is to remove primer-binding regions, as these regions will most likely be artificial (the primer sequence) rather than a real biological sequence. When your metabarcoding primers are the same as the barcoding ones (one or both), the in silico PCR will not be able to retrieve the amplicon sequence and it will not be incorporated in the reference database. To get around this issue, we have added in a pairwise global alignment function that can be run after the in silico PCR. This function will take all the sequences that were not incorporated in the database through the in silico PCR and align them to the results of the in silico PCR. You can set the thresholds of similarity and query cover in this function to determine what is considered a positive hit and be included in the reference database. Further testing needs to be done on this function to determine when false-positive hits will be an issue. We, therefore, recommend to use the option 'strict' for now, which will only include the sequence if the alignment starts or ends within the primer-binding region. To provide more information, you can use the help output within the terminal by typing: "crabs pga -h". Unfortunately, I haven't been able to include this to the README document, which I will try to do asap. So, please keep on the lookout for this.

Cheers,
GJ
