### ISSUE TITLE
Steps 5 onwards online for NCBI databases?

### ISSUE THREAD

**Issue by laninsky** [gjeunen/reference_database_creator#5]
Kia ora GJ - just checking in about steps 5 onwards - these don't seem to work on the MitoFish database because step 5 doesn't seem to work (generates a blank input.tsv, presumably because the database doesn't follow the structure of the NCBI database?).

**Comment by gjeunen** [comment]
Hello laninsky,

Just checking that with step 5 you are referring to generating a taxonomic lineage? If so, this should work for the MitoFish database. Could you check if the output from step 4 (in silico PCR) did not result in an empty document? If the output from step 4 is not empty, might you be able to paste the first couple of lines of that document as an attachment to your response? That way I can figure out what is going on.

Cheers,
GJ

**Comment by gjeunen** [comment]
I see... The reason why 'crabs assign_tax' code is not working, is because the header information for each sequence is different from the expected crabs format. What should happen when you download the MitoFish database through the crabs db_download function, is that it will format the downloaded fasta file automatically, which is a simple 2-line fasta format with the header as the accession number (please see attached an example of the MitoFish databases downloaded through crabs). 

![Screen Shot 2022-05-23 at 1 59 26 PM](https://user-images.githubusercontent.com/43122446/169729497-3e418cb3-4897-4a0b-9c71-bf96c5a5f03c.png)

A couple of reasons why the format might not match the crabs format (other than a bug in the code):
1) sequences were not downloaded through the crabs db_download function
2) the parameter --keep_original in crabs db_download was set to "yes" and the in silico PCR was conducted on this file

Before I dig into the code to find the bug, can you let me know if any of these 2 options apply to your data?

**Comment by laninsky** [comment]
Oh thanks GJ - yup 100% the second option, sorry! Assumed everything was formatted the correct way, whether the pared down file or the "complete mitogenome" file. We'll try again using the "modified" file, not the "original file" (I originally chose to use the original data because we lost less sequences due to the lack of primers on each end)

**Comment by gjeunen** [comment]
Great that it is solved! Though the number of sequences that are retained shouldn't be different between the original file and the formatted file. The only thing that crabs will do is to retrieve the accession number from each header, discard all other header info, and place the sequence on a single line. Can you check the number of sequences that are in the original file and the formatted file? If these are different, I'll try to look into it a bit more as to why the sequences were discarded.

**Comment by laninsky** [comment]
Ah - OK. The apparent difference in the file size was probably just the difference in header lengths. We bricked the original file (writing the output over it) so cannot go back to that easily unfortunately, but I think it just sounds like we were going slightly off-trail! (i.e. not worth your time to troubleshoot).

**Comment by gjeunen** [comment]
To not having to rerun your steps, you can import the output from step 4 using the db_import module and let crabs know where the accession number can be found. This function will format your file into the crabs format. From there you can run the assign_tax module.

**Comment by laninsky** [comment]
Thanks GJ! I think we might just run through the steps again - good practice - the nice thing is the mitofish database is quick!
