### ISSUE TITLE
taxID must be present after assign_tax step for the program to work?

### ISSUE THREAD

**Issue by timz0605** [gjeunen/reference_database_creator#52]
Hello Gert-Jan,

Starting another thread here since it's a slightly different question/issue. After some time in debugging and checking some of the source code, it appears that during the `assign_tax` step, the program will assign a NCBI taxID to all sequences in the database. However, some species might not have a taxID present, thus affecting the position of species information in the file and causing the program to abort. Also, sometimes in-house generated barcodes might not have a resolution fine enough, thus not having a taxID present. 

If this issue persists, after I append sequences in the `missing_taxa` to the main file, all steps after `assign_tax` will work fine, until the very last step where I am trying to format the database using `tax_format`, as I encounter the error code 
` File "/home/mjzhang/reference_database_creator/crabs", line 1279, in tax_format
    fasta = '>' + parts[0] + '\n' + parts[9] + '\n'
                                    ~~~~~^^^
IndexError: list index out of range`

Then to experience the code, I manually add the number "1" to all in-house barcodes in the taxID position, and then the `crabs tax_format` step works fine. My guessing is that although taxID information will not be retained in the last step when I am exporting the database into sintax format, the taxID will serve as a place holder as the function recognize the sequence as `parts[9]`?

**Comment by gjeunen** [comment]
Hello @timz0605,

Please see my answer in your previous post. CRABS does need information to species level to work properly across all its functions. If you have a sequence assigned to genus level, you could provide the undefined species taxonomic ID that corresponds to genus sp. This might not exist, however, and you'll need to create one in the names.dmp and nodes.dmp files. 

It is correct that the tax_format of sintax does not include the taxID information in the final output file. Since you're encountering these issues with in-house barcodes, might I suggest to run CRABS on the online sequences, export that file to SINTAX format. Afterwards, append your in-house sequences in SINTAX format to the CRABS reference database to create your final ref DB. You can copy-paste or use the `cat` command to accomplish this.

I hope this helps.

Best,
Gert-Jan

**Comment by gjeunen** [comment]
Hello @timz0605,

In the latest version (`crabs --version 1.0.0`), CRABS is capable of parsing accession numbers, as well as species names, synonyms, and unaccepted names to generate the taxonomic lineage. This should resolve the issue your encountering.

Best wishes,
Gert-Jan
