### ISSUE TITLE
embl download with vrt not working

### ISSUE THREAD

**Issue by laninsky** [gjeunen/reference_database_creator#6]
Kia ora GJ - hit another weird one - we've tried to download the vertebrate database (as the closest match to "fish") from embl but it doesn't seem to be pulling down anything. Sure we are just doing something wrong!

```
crabs db_download --source embl --database 'vrt*' --output embl_vrt.fasta --keep_original yes
```
ls in the directory:
```
   0 -rw-rw----+ 1 easry01p        uoo00105    0 May 23 09:24 embl_vrt.fasta
   0 -rw-rw----+ 1 easry01p        uoo00105    0 May 23 09:24 CRABS_embl_download.fasta
```

**Comment by laninsky** [comment]
100% better than any code I write, so not complaining! (and you can't help it if the databases themselves are not available!) I believe back in the good old days EMBL was mirrored to NCBI but I can't find any explicit confirmation that that is still true. If it is true, then people could just be directed to NCBI anyway.

**Comment by gjeunen** [comment]
I've uploaded the updated code to GitHub. I tested it on the human data set (smallest) and it should work. The only difference is that the files have a different name structure on this new FTP server. So, you will need to capitalise your input parameter to make this work.

Your code should now look something like this: 
```
crabs db_download --source embl --database 'VRT*' --output embl_vrt.fasta --keep_original yes
```

From my limited testing, I only observed partial overlap between EMBL and NCBI. However, this could be due to the input parameters for the NCBI download. Further testing is required to determine if this is indeed the case or if we could point people to using NCBI (faster + more specific search terms).
