### ISSUE TITLE
Save images from command line

### ISSUE THREAD

**Issue by gregdenay** [gjeunen/reference_database_creator#67]
Very nice tools, I've been using it to check different primers set on NCBI databases to predict performances in metabarcoding experiments and the data processing part works without problems.

I have a problem generating visualization on my system though.
I work on a debian server where I only have a command line (no GUI). CRABS is installed via conda.
It seems that the `crabs visualization` command should open a window allowing to save images, but that is not an option on my system. Is there a way to export the pictures directly from the command line in any of the usual formats (png, pdf, html)?

**Comment by gjeunen** [comment]
Hello @gregdenay,

Thank you very much for your message. Yes, the `crabs visualization` will open a window to save the figure, thereby enabling to set appropriate dimensions and file format. Unfortunately, CRABS cannot save the figures directly for now.

We're fully updating CRABS and hope to make this new version available in October. I'll make sure that a direct save method will be made available for the `crabs visualization`. Would this fit your time schedule?

Best wishes,
Gert-Jan

**Comment by gregdenay** [comment]
Hi, sounds great! It's not a critical feature but it would be nice.
cheers.

**Comment by hughcross** [comment]
Hi @gregdenay, sorry for chiming in late here. If you use the docker image to run `crabs visualization` it will output a file instead of opening a window. On our [Docker tutorial there is a section](https://github.com/gjeunen/reference_database_creator/blob/main/docker_intro/README.md#visualizations-using-the-docker-image) explaining this.

Of course, some servers have security issues with Docker, in which case you could try using [Singularity](https://docs.sylabs.io/guides/3.5/user-guide/introduction.html) to build the container. These don't have the issues that Docker containers do on servers. I think some of our users have used this. I am happy to help troubleshoot. Adding support for Singularity is on our to-do list.

**Comment by gregdenay** [comment]
Thanks for the tip with Docker! I'll look into that.
Maybe it would be doable to add the option to use `plt.savefig`instead of `plt.show` in the relevant functions.

**Comment by gjeunen** [comment]
Hello @gregdenay,

Apologies for the delay. 

`crabs --version 1.0.0` is now available and allows for the immediate saving of the figures by specifying the `--output` parameter. This version can now be downloaded manually by cloning the GitHub repository. We hope to get this new version also updated for the Docker container and conda package as soon as possible.

I hope this will help with the issue of running CRABS on a server.

Best wishes,
Gert-Jan
