### ISSUE TITLE
Issue with blast database generation

### ISSUE THREAD

**Issue by wpearman1996** [gjeunen/reference_database_creator#75]
Hi GJ,
I've been using crabs for making an aDNA metabarcoding database and have run into a few minor issues:
1) The pairwise global alignment takes a long time to run, I was wondering if crabs does any sort of dereplication under the hood early in the process, or if this could speed things up? For example, I've started including a dereplication step of both the merged databases and the post-insilico PCR files. I found that dropped the sequence count by about 50% - which seemed (i think?) to speed up the pairwise alignment.

2) When I went to generate a blast database I got the following error:
```
Error running makeblastdb BLAST Database creation error: Near line 73563, the local id is too long.  Its length is 63 but 
the maximum allowed local id length is 50.  Please find and correct all local ids that are too long.
, aborting analysis...
```

I got around this easily by running:
`awk -F'\t' 'length($1) <= 50' 16S_aligned.txt > 16S_aligned_lengthproc.txt`

But I figured it might be worth letting you know about anyway, especially as the line number the error occurred on was 36782 - so presumably there's some conversion to a fasta which doubles the line count - and then hits an error and outputs the fasta line number - rather than the database line number.

Anyway, all of that is to say that the issues were easily dealt with, but thought I'd let you know in case its useful.
Cheers,
William

**Comment by gjeunen** [comment]
Hello @wpearman1996,

Thank you for using CRABS and for reporting the bugs you encountered. It helps us tremendously in our attempt to improve the user experience for everyone. Please find my answers to your specific queries below:

1. CRABS does not run any dereplication prior to `--pairwise-global-alignment`. Since the CRABS *v 1.0.0* update, we have made sure the file structure is identical across all functions within CRABS from `--import` to `--export`. One of the main reasons for doing so was to enable users to run functions in any order (though we still recommend users to follow the CRABS workflow). If you are working with a large dataset to build a local database, I would indeed recommend running `--dereplicate` and `--filter` prior to `--in-silico-pcr` (only need to run it once, rather than twice when running after `--in-silico-pcr`). This would significantly reduce the number of sequences needed to be processed and speed up code execution. We have now specified this tip in the README documentation under section **5.4.1**.
2. Thank you for pointing out this error, which I hadn't yet come across. The restriction of 50 characters is implemented in the `makeblastdb` function from the BLAST+ suite that CRABS relies on. This is usually not an issue, since the sequence ID is restricted to the NCBI accession number for BLAST databases. However, when a sequence in the database is not submitted to NCBI, no accession number exists and CRABS generates an alternative sequence ID in the form of "CRABS_###_taxon_name" to ensure unique identifiers for each sequence. This alternative name most likely exceeded the 50 character threshold implemented in `makeblastdb`. With the latest CRABS version *v 1.0.5*, we have implemented a length filter of 50 characters for the sequence ID, thereby omitting the error you encountered.

I hope this helps :)

Best wishes,
Gert-Jan
