### ISSUE TITLE
error with --in-silico-pcr 

### ISSUE THREAD

**Issue by brachy2** [gjeunen/reference_database_creator#77]
Hi there,

I am trying to extract an amplicon region of the mitofish db  using the --in-silico-pcr function with crabs version 1.0.4 and running into the error pasted below. I downloaded the mitofish database using:

crabs --download-mitofish --output CRABS_Fish_mitofish_dl.fasta

I imported it successfully into CRABS using:
crabs --import --import-format mitofish --input fish/CRABS_Fish_mitofish_dl.fasta --names crabtax/names.dmp --nodes crabtax/nodes.dmp --acc2tax crabtax/nucl_gb.accession2taxid --output fish/CRABS_MITOFish_final.txt --ranks 'superkingdom;phylum;class;order;family;genus;species'

This is the error I get:
crabs --in-silico-pcr --input CRABS_MITOFish_final.txt --output CRABS_ALLherps_FINAL_V5.txt --forward GACCCTATGGAGCTTTAGAC --reverse CGCTGTTATCCCTADRGTAACT

Traceback (most recent call last):
  File "/mnt/home/picqsoph/reference_database_creator/crabs", line 847, in <module>
    crabs()
  File "/mnt/home/picqsoph/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/picqsoph/miniconda3/envs/py38/lib/python3.8/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/mnt/home/picqsoph/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/picqsoph/miniconda3/envs/py38/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/home/picqsoph/reference_database_creator/crabs", line 614, in crabs
    trimmed_seqs, untrimmed_seqs = cutadapt(console, columns, adapter, temp_input_path, fasta_dict, mismatch_, overlap, threads_)
  File "/mnt/ufs18/home-027/picqsoph/reference_database_creator/function/crabs_functions.py", line 1100, in cutadapt
    header = header.removesuffix(' rc')
AttributeError: 'str' object has no attribute 'removesuffix'

<img width="945" alt="Screenshot 2024-10-27 at 6 51 40 PM" src="https://github.com/user-attachments/assets/586f0d49-004d-4ecd-89b1-849c81bc77e3">

Please note that this is happening with different primers as well.  Other input files do work with this function (custom barcodes input files), so I think it is a formatting error with this input file, but I am not able to diagnose it. This is happening for NCBI downloaded files as well. I'd love to get some help with this! Thank you so much.

**Comment by gjeunen** [comment]
Hello @brachy2,

Thank you for using CRABS :)

The error you are encountering is due to an outdated version of Python. CRABS was built on Python3 v 3.11.7, but will run fine on any compatible Python3 version to the one it was built on. The `--in-silico-pcr` function makes use of a built-in Python attribute `removesuffix` that was introduced in Python3 v 3.9. However, the error specifies you are operating on Python3 v 3.8, which does not include this attribute. Hence, the error.

Once you update your Python3 version, everything should run smoothly. However, please reopen this issue if your problem persists after updating python.

You can check your python version using:

```{code-block} bash
python3 --version
```

To update python, you can use one of the following (depending on what you have installed and your OS):

MacOS (assuming homebrew is installed):

```{code-block} bash
brew install python
```

Linux:

```{code-block} bash
sudo apt update
sudo apt install python3
```

Once you have updated your python version check if it is higher than v 3.9:

```{code-block} bash
python3 --version
```

I hope this helps.

Best wishes,
Gert-Jan
